    Numpy Library

    NumPy is like a super-powered calculator for Python that can handle thousands of numbers at once, very fast. Instead of doing calculations one-by-one, NumPy does them all together.

In [1]:
fruits=['Apple', 'Banana', 'Cherry', 'Date']
fruits

['Apple', 'Banana', 'Cherry', 'Date']

In [2]:
fruits*2

['Apple', 'Banana', 'Cherry', 'Date', 'Apple', 'Banana', 'Cherry', 'Date']

In [3]:
nos=[1,2,3,4,5]
nos

[1, 2, 3, 4, 5]

In [4]:
nos*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
import numpy as np
arr=np.array(nos)
arr

array([1, 2, 3, 4, 5])

In [6]:
arr*2

array([ 2,  4,  6,  8, 10])

In [7]:
import numpy as np

marks_array=np.array([85, 90, 78, 92, 88])
marks_array

array([85, 90, 78, 92, 88])

In [8]:
marks_array[3]

np.int64(92)

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
zeros=np.zeros((4,5),dtype=int)

In [14]:
zeros+3

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
ones*2.4

array([[2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4]])

In [21]:
sequence=np.arange(0,51,10)
sequence

array([ 0, 10, 20, 30, 40, 50])

    We have marks of students for different subjects
        maths
        science
        english

    np.random.randint(
        0   =>  start_range
        101 =>  ending_range
        5   =>  no of random values to generate
    )

In [47]:
import numpy as np

In [46]:
maths=np.random.randint(35,101,5)
maths

array([67, 60, 53, 97, 89])

In [50]:
science=np.random.randint(35,101,5)
science

array([38, 60, 87, 60, 67])

In [51]:
english=np.random.randint(35,101,5)
english

array([79, 53, 94, 83, 63])

In [52]:
maths.shape

(5,)

In [ ]:
# Total Marks
total_marks=maths+science+english
total_marks

array([184, 173, 234, 240, 219])

In [54]:
# Calculate percentage
percentage=total_marks/3
percentage

array([61.33333333, 57.66666667, 78.        , 80.        , 73.        ])

In [56]:
# Find statistics
print(f'Highest in Maths: {maths.max()}')
print(f'Highest in Maths: {np.max(maths)}')

Highest in Maths: 97
Highest in Maths: 97


In [57]:
print(f'Average in english: {np.mean(english)}')

Average in english: 74.4


In [ ]:
# Marks of 4 students in 3 subjects (rows = students, columns = subjects)
# Columns: Maths, Science, English
class_marks = np.array([
    [85, 80, 75],   # Student 1: Rahul
    [90, 85, 88],   # Student 2: Priya
    [78, 82, 80],   # Student 3: Amit
    [92, 88, 85]    # Student 4: Sneha
])

In [59]:
print("Full Class Data:")
print(class_marks)

Full Class Data:
[[85 80 75]
 [90 85 88]
 [78 82 80]
 [92 88 85]]


In [60]:
class_marks.shape

(4, 3)

In [61]:
# Get specific data
print("\nRahul's marks:", class_marks[0])        # First row


Rahul's marks: [85 80 75]


    0   0     1   2
        [85, 80, 75],   # Student 1: Rahul
    1
        [90, 85, 88],   # Student 2: Priya
    2
        [78, 82, 80],   # Student 3: Amit
    3
        [92, 88, 85]

    85  =>  0,0
    80  =>  0,1
    75  =>  0,2
    82  =>  2,1

In [62]:
print("Everyone's Maths:", class_marks[:, 0])    # First column

Everyone's Maths: [85 90 78 92]


In [63]:
print("Priya's Science:", class_marks[1, 1])     # Specific cell

Priya's Science: 85


    2D array 
        Row-Wise    =>  axis=1
        Column-Wise =>  axis=0

In [65]:
# Student-wise total
student_totals = np.sum(class_marks, axis=1)  # axis=1 means row-wise
print("\nStudent totals:", student_totals)


Student totals: [240 263 240 265]


In [66]:
# Subject-wise total
subject_totals = np.sum(class_marks, axis=0)  # axis=0 means column-wise
print("Subject totals:", subject_totals)

Subject totals: [345 335 328]


    Declare
        np.array
        np.zeros
        np.ones
        np.random.randint
    Operation
        +
        -
        *
        /
    Dimension
        1D  =>  (5,) (3,)
        2D  =>  (6,4) (2,3)
        3D  =>  (2,3,4)
        4D
        5D
    Functions
        sum
        max
        min
        np
            np.sum
            np.count
            np.max
            np.min
            np.mean
    Slicing
        array[row,column]
        array[start_row_index:end_row_index:step,]

In [67]:
class_marks


array([[85, 80, 75],
       [90, 85, 88],
       [78, 82, 80],
       [92, 88, 85]])

In [69]:
class_marks[::2,::2]

array([[85, 75],
       [78, 80]])